app/controllers/subscriptions_controller.rb, app/controllers/users_controller.rb, app/models/subscription.rb, app/models/subscriptions_users.rb, app/models/user.rb, app/views/home/index.html.erb, app/views/subscriptions/show.html.erb, app/views/users/index.html.erb, config/routes.rb, db/migrate/20180724115953_create_subscriptions_users.rb, db/migrate/20180724133229_add_name_to_users.rb, db/schema.rb, db/seeds.rb
Changed model to 1 to many, redid seeds.rb file, added feature for user to choose subscription plan and chosen plan is reflected in the user profile.
=> Changed model, edited files, user subscription works.

app/models/user.rb, config/environments/development.rb, config/initializers/devise.rb, db/migrate/20180724133229_add_name_to_users.rb, db/migrate/20180725132711_add_email_helper.rb, db/migrate/20180725133651_add_confirmable_to_devise.rb, db/migrate/20180725134037_add_lockable_to_devise.rb, db/migrate/20180725135433_add_unconfirmed_email.rb, db/schema.rb
New:
When registering, confirmation email is sent.
Bug: 
Confirmation Token is invalid after user clicks on email link
=> Action Mailer sends email now

app/assets/stylesheets/application.scss, app/assets/stylesheets/subscriptions.scss, app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/unlocks/new.html.erb, app/views/home/index.html.erb, app/views/layouts/application.html.erb, app/views/subscriptions/index.html.erb, app/views/subscriptions/show.html.erb, app/views/users/index.html.erb
Added containers to html body. 
Centered all body text. 
Converted some links into buttons.
Added new font family to h1, h2 and buttons. 
Need to test styles and layout for pages that require user login. Unable to login for now.
=> applied css styles to body

app/controllers/home_controller.rb, app/controllers/subscriptions_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/home/index.html.erb, app/views/home/profile.html.erb, app/views/subscriptions/index.html.erb, app/views/subscriptions/show.html.erb, config/routes.rb, db/seeds.rb
Commented out confirmable, lockable from models/user.rb
Done with subscriptions for new, edit and delete.
=> Commented out confirmable, lockable. Done with subscriptions

app/assets/stylesheets/styles/globals.scss, app/views/devise/sessions/new.html.erb, app/views/partials/_navbar.html.erb
=> boostrapped user login form

app/controllers/home_controller.rb, app/controllers/subscriptions_controller.rb, config/routes.rb
=> Minor edit regarding "unable to get id of undefined"

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
=> fixed forms

app/assets/stylesheets/styles/globals.scss, app/assets/stylesheets/styles/index.scss, app/views/home/profile.html.erb
=> Style fixes

app/views/partials/_footer.html.erb
=> footer fix attempt 2

app/assets/stylesheets/styles/globals.scss, app/assets/stylesheets/styles/index.scss
=> index styles

app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/home/profile.html.erb
=> container class fix

app/assets/stylesheets/styles/globals.scss
=> css for container fix

app/controllers/menu_controller.rb, app/views/home/profile.html.erb, db/migrate/20180724133229_add_name_to_users.rb, db/migrate/20180724141448_add_price_to_subscriptions.rb
=> Edited profile.html.erb, migration files

db/migrate/20180724133229_add_name_to_users.rb, db/migrate/20180724141448_add_price_to_subscriptions.rb, db/migrate/20180727080926_add_columns_to_users.rb, db/migrate/20180727081115_add_menu_to_subscriptions.rb, db/schema.rb
=> Added columns to users and also to subscriptions. 

db/schema.rb
=> minor edit of schema

app/assets/stylesheets/styles/footer.scss
=> this footer fix *should* work!

app/assets/stylesheets/styles/index.scss, app/views/home/profile.html.erb, app/views/subscriptions/index.html.erb
=> Changed Subscription to Menu

app/controllers/subscriptions_controller.rb, app/views/menus/index.html.erb, app/views/partials/_navbar.html.erb, app/views/subscriptions/index.html.erb
menus/index.html.erb is currently rendering static, not dynamic.
Need to work on overall UX flow of our app (for purchase process)
=> Swapped contents of subscriptions/index.html.erb and menus/index.html.erb

app/controllers/home_controller.rb, app/controllers/menus_controller.rb, app/controllers/subscriptions_controller.rb, app/helpers/application_helper.rb, app/models/user.rb, app/views/home/profile.html.erb, app/views/menus/delivery.html.erb, app/views/menus/index.html.erb, app/views/menus/payment.html.erb, app/views/menus/show.html.erb, app/views/subscriptions/index.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20180727080926_add_columns_to_users.rb, db/migrate/20180729203349_add_delivery_arranged_to_users.rb, db/schema.rb
1. Added form page to arrange delivery and update DB based on input.
2. Updated users table with another column for "delivery_arranged - boolean".
3. <div class="container mt-5 pt-5"> being used for most views pages.
=> MAJOR COMMIT, PLEASE RUN "rails db:reset"

app/views/devise/shared/_links.html.erb, app/views/home/profile.html.erb, app/views/partials/_navbar.html.erb
=> fix link and redo profile page

app/views/menus/index.html.erb
=> added menu page margin

app/assets/stylesheets/styles/index.scss, app/views/menus/delivery.html.erb
=> changed form fields to match login

app/views/menus/index.html.erb
=> centralize button on menu page

app/views/menus/delivery.html.erb
=> delivery page margin

app/controllers/home_controller.rb, app/controllers/menus_controller.rb, app/views/home/profile.html.erb, app/views/menus/delivery.html.erb, app/views/menus/index.html.erb, config/routes.rb
=> Backend profile fix

app/views/menus/payment.html.erb
=> payment page button styled

app/views/devise/registrations/edit.html.erb
=> edit account minor edits
